image: java:openjdk-8-jdk
script:
    - echo "deb http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main" >> /etc/apt/sources.list.d/maven3.list
    - echo "deb-src http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main" >> /etc/apt/sources.list.d/maven3.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys  B70731143DD9F856
    - apt-get update
    - apt-get -y install python-pip
    - apt-get install -y maven3
    - mvn3 install
