image: java:openjdk-8-jdk
script:
    - echo "deb http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main" >> /etc/apt/sources.list.d/maven3.list
    - echo "deb-src http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main" >> /etc/apt/sources.list.d/maven3.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys  B70731143DD9F856
    - apt-get update
    - apt-get install -y maven3
notify:
    email:
        recipients:
            - song@polyvore.com
            - jiang@polyvore.com
        on_success: true
        on_failure: true
publish:
    s3:
        acl: private
        bucket: $$S3_DOCUMENTATION_BUCKET
        region: $$S3_DOCUMENTATION_REGION
        source: mahout/mr/pom.xml
        target: $$S3_DOCUMENTATION_DIR
        recursive: true
        access_key: $$AWS_KEY
        secret_key: $$AWS_SECRET
